---
title: "chapter3"
author: "Matthew Emery"
date: "June 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rethinking)
library(tidyverse)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

```{r}
data(homeworkch3)
```

```{r}
sum(birth1) + sum(birth2)
```

## Easy Questions

```{r}
p_grid <- seq(from)
```

```{r}

```

## Hard Questions

### Question 1

```{r}
p_grid <- seq(from = 0, to = 1, length.out = 1000)
prior <- rep(1, 1000)
likelihood <- dbinom(sum(birth1) + sum(birth2), size = 200, prob = p_grid)
posterior <- likelihood * prior
posterior <- posterior * sum(posterior)
```

```{r}
max(posterior)
```

```{r}
p_grid[which.max(posterior)]
```

```{r}
111/200
```


```{r}
ggplot(as_tibble(p_grid, posterior), aes(x = p_grid, y =  posterior)) +
  geom_line()
```

### Question 2

```{r}
posterior_samples <- sample(p_grid, 10000, replace = TRUE, prob = posterior)
```

```{r}
HPDI(posterior_samples, 0.5)
```

```{r}
HPDI(posterior_samples)
```

```{r}
HPDI(posterior_samples, 0.97)
```

### Question 3

```{r}
simulations <- rbinom(10000, 200, prob = posterior_samples)
```

```{r}
dens(simulations)
```

It looks pretty close, but it is a board distribution

### Question 4

```{r}
likelihood <- dbinom(sum(birth1), size = 100, prob = p_grid)
```


