---
title: "Chapter 5"
author: "Matt Emery"
date: "November 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Easy.

**5E1.** Which of the linear models below are multiple linear regressions?
(1) $μ_i = α + βx_i$
(2) $μ_i = β_xx_i + β_zz_i$
(3) $μ_i = α + β(x_i − z_i)$
(4) $μ_i = α + β_xx_i + β_zz_i$

(2) and (4)

**5E2.** Write down a multiple regression to evaluate the claim: *Animal diversity is linearly related to latitude, but only after controlling for plant diversity.* You just need to write down the model definition.

**5E3.** Write down a multiple regression to evaluate the claim: Neither amount of funding nor size of laboratory is by itself a good predictor of time to PhD degree; but together these variables are both positively associated with time to degree. Write down the model definition and indicate which side of zero each slope parameter should be on.

**5E4.** Suppose you have a single categorical predictor with 4 levels (unique values), labeled A, B, C and D. Let A i be an indicator variable that is 1 where case i is in category A. Also suppose $B_i$ , $C_i$ , and $D_i$ for the other categories. Now which of the following linear models are inferentially equivalent ways to include the categorical variable in a regression? Models are inferentially equivalent when it’s possible to compute one posterior distribution from the posterior distribution of another model.

(1) $μ_i = α + β_AA_i + β_BB_i + β_DD_i$
(2) $μ i = α + β_AA_i + β_BB_i + β_CC_i + β_DD_i$
(3) $\mu_i = \alpha + \beta_BB_i + \beta_CC_i + \beta_DD_i$
(4) $μ_i = α_AA_i + α_B_i + α_CC_i + α_DD_i$
(5) $μ_i = α_A(1 − B_i − C_i − D_i) + α_BB_i + α_CC_i + α_DD_i$

## Medium.

**5M1.** Invent your own example of a spurious correlation. An outcome variable should be correlated with both predictor variables. But when both predictors are entered in the same model, the correlation between the outcome and one of the predictors should mostly vanish (or at least be greatly reduced).

**5M2.** Invent your own example of a masked relationship. An outcome variable should be correlated with both predictor variables, but in opposite directions. And the two predictor variables should be correlated with one another.

**5M3.** It is sometimes observed that the best predictor of fire risk is the presence of firefighters—States and localities with many firefighters also have more fires. Presumably firefighters do not cause fires. Nevertheless, this is not a spurious correlation. Instead fires cause firefighters. Consider the same reversal of causal inference in the context of the divorce and marriage data. How might a high divorce rate cause a higher marriage rate? Can you think of a way to evaluate this relationship, using multiple regression?

**5M4.** In the divorce data, States with high numbers of Mormons (members of The Church of Jesus Christ of Latter-day Saints, LDS) have much lower divorce rates than the regression models expected. Find a list of LDS population by State and use those numbers as a predictor variable, predicting divorce rate using marriage rate, median age at marriage, and percent LDS population (possibly standardized). You may want to consider transformations of the raw percent LDS variable.

**5M5.** One way to reason through multiple causation hypotheses is to imagine detailed mechanisms through which predictor variables may influence outcomes. For example, it is sometimes argued that the price of gasoline (predictor variable) is positively associated with lower obesity rates (outcome variable). However, there are at least two important mechanisms by which the price of gas could reduce obesity. First, it could lead to less driving and therefore more exercise. Second, it could lead to less driving, which leads to less eating out, which leads to less consumption of huge restaurant meals. Can you outline one or more multiple regressions that address these two mechanisms? Assume you
can have any predictor data you need.

## Hard.

All three exercises below use the same data, `data(foxes)` (part of rethinking ). 81 The urban fox (*Vulpes vulpes*) is a successful exploiter of human habitat. Since urban foxes move in packs and defend territories, data on habitat quality and population density is also included. The data frame has five columns:
(1) `group` : Number of the social group the individual fox belongs to
(2) `avgfood` : The average amount of food available in the territory
(3) `groupsize` : The number of foxes in the social group
(4) `area` : Size of the territory
(5) `weight` : Body weight of the individual fox

**5H1.** Fit two bivariate Gaussian regressions, using map : (1) body weight as a linear function of territory size ( area ), and (2) body weight as a linear function of groupsize . Plot the results of these regressions, displaying the MAP regression line and the 95% interval of the mean. Is either variable important for predicting fox body weight?

**5H2.** Now fit a multiple linear regression with weight as the outcome and both area and groupsize as predictor variables. Plot the predictions of the model for each predictor, holding the other predictor constant at its mean. What does this model say about the importance of each variable? Why do you get different results than you got in the exercise just above?

**5H3.** Finally, consider the avgfood variable. Fit two more multiple regressions: (1) body weight as an additive function of avgfood and groupsize , and (2) body weight as an additive function of all three variables, avgfood and groupsize and area . Compare the results of these models to the previous models you’ve fit, in the first two exercises. (a) Is avgfood or area a better predictor of body weight? If you had to choose one or the other to include in a model, which would it be? Support your assessment with any tables or plots you choose. (b) When both avgfood or area are in the same model, their effects are reduced (closer to zero) and their standard errors are larger than when they are included in separate models. Can you explain this result?
